name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://Abdulrhman37:$HF@huggingface.co/spaces/Abdulrhman37/mlops_text_summarizer
      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://huggingface.co/spaces/Abdulrhman37/mlops_text_summarizer main
